#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     encoderMotor,  tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     nonEncoderMotor, tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	nmotorEncoder[encoderMotor] = 0;
	motor[encoderMotor] = 100;
	float dummyVariable = 0.0;
	while(true)
	{
		dummyVariable = nmotorEncoder[encoderMotor];
		nxtDisplayTextLine(3,"%d",dummyVariable);
	}

}
