#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRLeft,         sensorI2CCustom)
#pragma config(Sensor, S3,     IRRight,        sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     launcher,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     frontLow,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    auto1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    auto2,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    auto4,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Define class variables
const float MAX_JOYSTICK = 127.0;
const float MOTOR_POWER = 100;
const float SLOW_MOTOR_POWER = 30;
bool fasterSpeed = true;


//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{

  // Place code here to initialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}

/*
Does the calculation to turn the joystick values into motor values
*/
int getMotorOutput(int joystickValue){

	int directionValue = joystickValue / abs(joystickValue);
 	float ratio = (joystickValue * joystickValue) / (MAX_JOYSTICK * MAX_JOYSTICK);
 	if(fasterSpeed){
		return (ratio * (MOTOR_POWER)) * directionValue;
	}
	else{
		return (ratio * (SLOW_MOTOR_POWER)) * directionValue;
	}
}

/*
Method that assigns the correct values to drive the motors
*/
void drive()  {
	setSpeed();
	motor[right] = getMotorOutput(joystick.joy1_y2);
	motor[left] = getMotorOutput(joystick.joy1_y1);
}

void moveBallLift()  {
	if(joy1Btn(8)){
		motor[lift] = 100;
	}
	else if(joy1Btn(7)){
		motor[lift] = -100;
	}
	else(){
		motor[lift] = 0;
	}
}

void ballCollection(){
	if(joy1Btn(2)){
		motor[collector] = 100;
	}
	else if(joy1Btn(4)){
		motor[collector] = -100;
	}
	else(){
		motor[collector] = 0;
	}
}

void launchBall(){
	if(joy1Btn(3)){
		motor[launcher] = 100;
	}
	else if(joy1Btn(1)){
		motor[launcher] = -100;
	}
	else(){
		motor[launcher] = 0;
	}
}


task main()
{
	// wait for start of tele-op phase
	waitForStart();

	bFloatDuringInactiveMotorPWM = false;

  //Game loop for robot
  while (true){
  	getJoystickSettings(joystick);
		drive();
		moveBallLift();
		launchBall();
		ballCollection();
	}
}
