#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRLeft,         sensorI2CCustom)
#pragma config(Sensor, S3,     IRRight,        sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     swing,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     topCollector,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     bottomCollector, tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    topGate,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    tube,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    auto4,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Define class variables

//Motor Values
const float MAX_JOYSTICK = 127.0;
const float MOTOR_POWER = 100;
const float SLOW_MOTOR_POWER = 50;
const float BALL_LIFT_UP = 100;
const float BALL_LIFT_DOWN = -100;
const float BALL_COLLECTOR_UP = 100;
const float BALL_COLLECTOR_DOWN = -100;
const float SWING_OUT = 100;

bool fasterSpeed = true;

//Servo Values
const float TOP_GATE_UP = 140;
const float TOP_GATE_DOWN = 255;
const float TUBE_SERVO_UP = 85;
const float TUBE_SERVO_DOWN = 170;
const float TUBE_SERVO_RAMP = 135;

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{

  // Place code here to initialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	servoTarget[topGate] = TOP_GATE_DOWN;
	servoTarget[tube] = TUBE_SERVO_UP;

  	return;
}

/*
Does the calculation to turn the joystick values into motor values
*/
int getMotorOutput(int joystickValue){

	int directionValue = joystickValue / abs(joystickValue);
 	float ratio = (joystickValue * joystickValue) / (MAX_JOYSTICK * MAX_JOYSTICK);
 	if(fasterSpeed){
		return (ratio * (MOTOR_POWER)) * directionValue;
	}
	else{
		return (ratio * (SLOW_MOTOR_POWER)) * directionValue;
	}
}

/*Sets the speed between fast and slow
*/
void setSpeed(){
	if(joy1Btn(1)){
		fasterSpeed = false;
	}
	else if(joy1Btn(3)){
		fasterSpeed = true;
	}
}

/*
Method that assigns the correct values to drive the motors
*/
void drive()  {
	setSpeed();
	motor[right] = getMotorOutput(joystick.joy1_y2);
	motor[left] = getMotorOutput(joystick.joy1_y1);
}

void moveSwing()  {
	if(joy2Btn(3)){
		motor[swing] = SWING_OUT;
	}
	else if(joy2Btn(1)){
		motor[swing] = SWING_OUT * -1;
	}
	else{
		motor[swing] = 0;
	}
}

void moveBallLift()  {
	if(joy2Btn(2)){
		motor[lift] = BALL_LIFT_UP;
	}
	else if(joy2Btn(4)){
		motor[lift] = BALL_LIFT_DOWN;
	}
	else{
		motor[lift] = 0;
	}
}

void ballCollection(){

	if(joy2Btn(8)){

		motor[topCollector] = BALL_COLLECTOR_UP;
		motor[bottomCollector] = BALL_COLLECTOR_UP;
	}
	else if(joy2Btn(7)){
		motor[topCollector] = BALL_COLLECTOR_DOWN;
		motor[bottomCollector] = BALL_COLLECTOR_DOWN;
	}
	else{
		motor[topCollector] = 0;
		motor[bottomCollector] = 0;
	}
}

void moveGate(){
	if(joy2Btn(6)){
		servoTarget[topGate] = TOP_GATE_UP;
	}
	else if(servoValue(topGate) < 145){
		servoTarget[topGate] = TOP_GATE_DOWN;
	}
}

void moveTubeServo(){
	if(joy1Btn(4)){
		servoTarget[tube] = TUBE_SERVO_UP;
	}
	if(joy1Btn(7)){
		servoTarget[tube] = TUBE_SERVO_RAMP;
	}
	else if(joy1Btn(2)){
		servoTarget[tube] = TUBE_SERVO_DOWN;
	}
}


task main()
{
	// wait for start of tele-op phase
	waitForStart();
	initializeRobot();

	bFloatDuringInactiveMotorPWM = false;

  //Game loop for robot
  while (true){
  	getJoystickSettings(joystick);

		drive();
		moveBallLift();
		ballCollection();
		moveGate();
		moveTubeServo();
		moveSwing();
	}
}
